backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "src/assets"
public_folder: "/assets"

collections:
- name: "blog" # Used in routes, e.g., /admin/collections/blog
  label: "Blog" # Used in the UI
  folder: "src/pages/blog" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
  - {label: "Title", name: "title", widget: "string", required: true}
  - {label: "Blog Creater Name", name: "blogerName", widget: "string", required: true}
  - {label: "Description", name: "description", widget: "string"}
  - {label: "Hero Image", name: "heroImage", widget: "image"}
  - {label: "Body", name: "body", widget: "markdown"}

  
